# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel

from .send_message_error import SendMessageError


class SendMessageErrors(BaseModel):
    recipients: list[SendMessageError] | None = None
