# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel

from .send_message_errors import SendMessageErrors


class SendMessageResponse(BaseModel):
    errors: SendMessageErrors | None = None
    timestamp: str
