# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel


class SendMessageError(BaseModel):
    number: str | None = None
    reason: str | None = None
    username: str | None = None
    uuid: str | None = None
