# generated by datamodel-codegen:
#   filename:  json-models.json
#   timestamp: 2026-03-02T01:05:58+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Base64Str, BaseModel, Field


class AdminDelete(BaseModel):
    target_author: str = Field(..., alias="targetAuthor", deprecated=True)
    target_author_number: str = Field(..., alias="targetAuthorNumber")
    target_author_uuid: str = Field(..., alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")


class Answer(BaseModel):
    id: int
    opaque: str


class Attachment(BaseModel):
    content_type: str = Field(..., alias="contentType")
    filename: str
    id: str
    size: int
    width: int
    height: int
    caption: str
    upload_timestamp: int = Field(..., alias="uploadTimestamp")


class AttachmentData(BaseModel):
    data: str | None = None


class Busy(BaseModel):
    id: int


class ContactAddress(BaseModel):
    type: str
    label: str
    street: str
    pobox: str
    neighborhood: str
    city: str
    region: str
    postcode: str
    country: str


class ContactAvatar(BaseModel):
    attachment: Attachment
    is_profile: bool = Field(..., alias="isProfile")


class ContactEmail(BaseModel):
    value: str
    type: str
    label: str


class ContactName(BaseModel):
    nickname: str
    given: str
    family: str
    prefix: str
    suffix: str
    middle: str


class ContactPhone(BaseModel):
    value: str
    type: str
    label: str


class Error(BaseModel):
    message: str | None = None
    type: str | None = None


class Gradient(BaseModel):
    start_color: str = Field(..., alias="startColor")
    end_color: str = Field(..., alias="endColor")
    colors: list[str]
    positions: list[float]
    angle: int


class GroupInfo(BaseModel):
    group_id: str = Field(..., alias="groupId")
    group_name: str = Field(..., alias="groupName")
    revision: int
    type: str


class Hangup(BaseModel):
    id: int
    type: str
    device_id: int = Field(..., alias="deviceId")


class IceUpdate(BaseModel):
    id: int
    opaque: str


class Internal(BaseModel):
    capabilities: list[str] | None = None
    unidentified_access_mode: str | None = Field(None, alias="unidentifiedAccessMode")
    shares_phone_number: bool | None = Field(None, alias="sharesPhoneNumber")
    discoverable_by_phonenumber: bool | None = Field(
        None, alias="discoverableByPhonenumber"
    )


class Mention(BaseModel):
    name: str = Field(..., deprecated=True)
    number: str
    uuid: str
    start: int
    length: int


class Offer(BaseModel):
    id: int
    type: str
    opaque: str


class Payment(BaseModel):
    note: str
    receipt: Base64Str


class PinMessage(BaseModel):
    target_author: str = Field(..., alias="targetAuthor", deprecated=True)
    target_author_number: str = Field(..., alias="targetAuthorNumber")
    target_author_uuid: str = Field(..., alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    pin_duration_seconds: int = Field(..., alias="pinDurationSeconds")


class PollCreate(BaseModel):
    question: str
    allow_multiple: bool = Field(..., alias="allowMultiple")
    options: list[str]


class PollTerminate(BaseModel):
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")


class PollVote(BaseModel):
    author: str = Field(..., deprecated=True)
    author_number: str = Field(..., alias="authorNumber")
    author_uuid: str = Field(..., alias="authorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    option_indexes: list[int] = Field(..., alias="optionIndexes")
    vote_count: int = Field(..., alias="voteCount")


class Preview(BaseModel):
    url: str
    title: str
    description: str
    image: Attachment


class Profile(BaseModel):
    last_update_timestamp: int | None = Field(None, alias="lastUpdateTimestamp")
    given_name: str | None = Field(None, alias="givenName")
    family_name: str | None = Field(None, alias="familyName")
    about: str | None = None
    about_emoji: str | None = Field(None, alias="aboutEmoji")
    has_avatar: bool | None = Field(None, alias="hasAvatar")
    mobile_coin_address: str | None = Field(None, alias="mobileCoinAddress")


class QuotedAttachment(BaseModel):
    content_type: str = Field(..., alias="contentType")
    filename: str
    thumbnail: Attachment | None = None


class Reaction(BaseModel):
    emoji: str
    target_author: str = Field(..., alias="targetAuthor", deprecated=True)
    target_author_number: str = Field(..., alias="targetAuthorNumber")
    target_author_uuid: str = Field(..., alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    is_remove: bool = Field(..., alias="isRemove")


class ReceiptMessage(BaseModel):
    when: int
    is_delivery: bool = Field(..., alias="isDelivery")
    is_read: bool = Field(..., alias="isRead")
    is_viewed: bool = Field(..., alias="isViewed")
    timestamps: list[int]


class RecipientAddress(BaseModel):
    uuid: str
    number: str
    username: str


class RemoteDelete(BaseModel):
    timestamp: int


class Type(Enum):
    success = "SUCCESS"
    network_failure = "NETWORK_FAILURE"
    unregistered_failure = "UNREGISTERED_FAILURE"
    identity_failure = "IDENTITY_FAILURE"
    rate_limit_failure = "RATE_LIMIT_FAILURE"
    invalid_pre_key_failure = "INVALID_PRE_KEY_FAILURE"


class SendMessageResult(BaseModel):
    recipient_address: RecipientAddress = Field(..., alias="recipientAddress")
    group_id: str | None = Field(None, alias="groupId")
    type: Type
    token: str | None = None
    retry_after_seconds: int | None = Field(None, alias="retryAfterSeconds")


class SharedContact(BaseModel):
    name: ContactName
    avatar: ContactAvatar | None = None
    phone: list[ContactPhone] | None = None
    email: list[ContactEmail] | None = None
    address: list[ContactAddress] | None = None
    organization: str


class Sticker(BaseModel):
    pack_id: str = Field(..., alias="packId")
    sticker_id: int = Field(..., alias="stickerId")


class StoryContext(BaseModel):
    author_number: str = Field(..., alias="authorNumber")
    author_uuid: str = Field(..., alias="authorUuid")
    sent_timestamp: int = Field(..., alias="sentTimestamp")


class Type1(Enum):
    contacts_sync = "CONTACTS_SYNC"
    groups_sync = "GROUPS_SYNC"
    request_sync = "REQUEST_SYNC"


class SyncReadMessage(BaseModel):
    sender: str | None = Field(None, deprecated=True)
    sender_number: str | None = Field(None, alias="senderNumber")
    sender_uuid: str | None = Field(None, alias="senderUuid")
    timestamp: int | None = None


class TextAttachment(BaseModel):
    text: str
    style: str | None = None
    text_foreground_color: str | None = Field(None, alias="textForegroundColor")
    text_background_color: str | None = Field(None, alias="textBackgroundColor")
    preview: Preview | None = None
    background_gradient: Gradient | None = Field(None, alias="backgroundGradient")
    background_color: str | None = Field(None, alias="backgroundColor")


class TextStyle(BaseModel):
    style: str
    start: int
    length: int


class TypingMessage(BaseModel):
    action: str | None = None
    timestamp: int | None = None
    group_id: str | None = Field(None, alias="groupId")


class UnpinMessage(BaseModel):
    target_author: str = Field(..., alias="targetAuthor", deprecated=True)
    target_author_number: str = Field(..., alias="targetAuthorNumber")
    target_author_uuid: str = Field(..., alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")


class CallMessage(BaseModel):
    offer_message: Offer | None = Field(None, alias="offerMessage")
    answer_message: Answer | None = Field(None, alias="answerMessage")
    busy_message: Busy | None = Field(None, alias="busyMessage")
    hangup_message: Hangup | None = Field(None, alias="hangupMessage")
    ice_update_messages: list[IceUpdate] | None = Field(None, alias="iceUpdateMessages")


class Contact(BaseModel):
    number: str | None = None
    uuid: str | None = None
    username: str | None = None
    name: str | None = None
    given_name: str | None = Field(None, alias="givenName")
    family_name: str | None = Field(None, alias="familyName")
    nick_name: str | None = Field(None, alias="nickName")
    nick_given_name: str | None = Field(None, alias="nickGivenName")
    nick_family_name: str | None = Field(None, alias="nickFamilyName")
    note: str | None = None
    color: str | None = None
    is_blocked: bool | None = Field(None, alias="isBlocked")
    is_hidden: bool | None = Field(None, alias="isHidden")
    message_expiration_time: int | None = Field(None, alias="messageExpirationTime")
    profile_sharing: bool | None = Field(None, alias="profileSharing")
    unregistered: bool | None = None
    profile: Profile | None = None
    internal: Internal | None = None


class Quote(BaseModel):
    id: int
    author: str = Field(..., deprecated=True)
    author_number: str = Field(..., alias="authorNumber")
    author_uuid: str = Field(..., alias="authorUuid")
    text: str
    mentions: list[Mention] | None = None
    attachments: list[QuotedAttachment]
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")


class StoryMessage(BaseModel):
    allows_replies: bool = Field(..., alias="allowsReplies")
    group_id: str | None = Field(None, alias="groupId")
    file_attachment: Attachment | None = Field(None, alias="fileAttachment")
    text_attachment: TextAttachment | None = Field(None, alias="textAttachment")


class SyncStoryMessage(BaseModel):
    destination_number: str = Field(..., alias="destinationNumber")
    destination_uuid: str = Field(..., alias="destinationUuid")
    allows_replies: bool = Field(..., alias="allowsReplies")
    group_id: str | None = Field(None, alias="groupId")
    file_attachment: Attachment | None = Field(None, alias="fileAttachment")
    text_attachment: TextAttachment | None = Field(None, alias="textAttachment")
    data_message: Any = Field(..., alias="dataMessage")


class DataMessage(BaseModel):
    timestamp: int
    message: str
    expires_in_seconds: int = Field(..., alias="expiresInSeconds")
    is_expiration_update: bool | None = Field(None, alias="isExpirationUpdate")
    view_once: bool | None = Field(None, alias="viewOnce")
    reaction: Reaction | None = None
    quote: Quote | None = None
    payment: Payment | None = None
    mentions: list[Mention] | None = None
    previews: list[Preview] | None = None
    attachments: list[Attachment] | None = None
    sticker: Sticker | None = None
    remote_delete: RemoteDelete | None = Field(None, alias="remoteDelete")
    contacts: list[SharedContact] | None = None
    poll_create: PollCreate | None = Field(None, alias="pollCreate")
    poll_vote: PollVote | None = Field(None, alias="pollVote")
    poll_terminate: PollTerminate | None = Field(None, alias="pollTerminate")
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")
    group_info: GroupInfo | None = Field(None, alias="groupInfo")
    story_context: StoryContext | None = Field(None, alias="storyContext")
    pin_message: PinMessage | None = Field(None, alias="pinMessage")
    unpin_message: UnpinMessage | None = Field(None, alias="unpinMessage")
    admin_delete: AdminDelete | None = Field(None, alias="adminDelete")


class EditMessage(BaseModel):
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    data_message: DataMessage = Field(..., alias="dataMessage")


class SyncDataMessage(BaseModel):
    destination: str = Field(..., deprecated=True)
    destination_number: str = Field(..., alias="destinationNumber")
    destination_uuid: str = Field(..., alias="destinationUuid")
    edit_message: EditMessage | None = Field(None, alias="editMessage")
    timestamp: int
    message: str
    expires_in_seconds: int = Field(..., alias="expiresInSeconds")
    is_expiration_update: bool | None = Field(None, alias="isExpirationUpdate")
    view_once: bool | None = Field(None, alias="viewOnce")
    reaction: Reaction | None = None
    quote: Quote | None = None
    payment: Payment | None = None
    mentions: list[Mention] | None = None
    previews: list[Preview] | None = None
    attachments: list[Attachment] | None = None
    sticker: Sticker | None = None
    remote_delete: RemoteDelete | None = Field(None, alias="remoteDelete")
    contacts: list[SharedContact] | None = None
    poll_create: PollCreate | None = Field(None, alias="pollCreate")
    poll_vote: PollVote | None = Field(None, alias="pollVote")
    poll_terminate: PollTerminate | None = Field(None, alias="pollTerminate")
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")
    group_info: GroupInfo | None = Field(None, alias="groupInfo")
    story_context: StoryContext | None = Field(None, alias="storyContext")
    pin_message: PinMessage | None = Field(None, alias="pinMessage")
    unpin_message: UnpinMessage | None = Field(None, alias="unpinMessage")
    admin_delete: AdminDelete | None = Field(None, alias="adminDelete")
    data_message: Any = Field(..., alias="dataMessage")


class SyncMessage(BaseModel):
    sent_message: SyncDataMessage | None = Field(None, alias="sentMessage")
    sent_story_message: SyncStoryMessage | None = Field(None, alias="sentStoryMessage")
    blocked_numbers: list[str] | None = Field(None, alias="blockedNumbers")
    blocked_group_ids: list[str] | None = Field(None, alias="blockedGroupIds")
    read_messages: list[SyncReadMessage] | None = Field(None, alias="readMessages")
    type: Type1 | None = None


class MessageEnvelope(BaseModel):
    source: str | None = Field(None, deprecated=True)
    source_number: str | None = Field(None, alias="sourceNumber")
    source_uuid: str | None = Field(None, alias="sourceUuid")
    source_name: str | None = Field(None, alias="sourceName")
    source_device: int | None = Field(None, alias="sourceDevice")
    timestamp: int | None = None
    server_received_timestamp: int | None = Field(None, alias="serverReceivedTimestamp")
    server_delivered_timestamp: int | None = Field(
        None, alias="serverDeliveredTimestamp"
    )
    data_message: DataMessage | None = Field(None, alias="dataMessage")
    edit_message: EditMessage | None = Field(None, alias="editMessage")
    story_message: StoryMessage | None = Field(None, alias="storyMessage")
    sync_message: SyncMessage | None = Field(None, alias="syncMessage")
    call_message: CallMessage | None = Field(None, alias="callMessage")
    receipt_message: ReceiptMessage | None = Field(None, alias="receiptMessage")
    typing_message: TypingMessage | None = Field(None, alias="typingMessage")


class SchemaCatalog(BaseModel):
    admin_delete: AdminDelete | None = Field(None, alias="adminDelete")
    attachment: Attachment | None = None
    attachment_data: AttachmentData | None = Field(None, alias="attachmentData")
    call_message: CallMessage | None = Field(None, alias="callMessage")
    contact: Contact | None = None
    contact_address: ContactAddress | None = Field(None, alias="contactAddress")
    contact_avatar: ContactAvatar | None = Field(None, alias="contactAvatar")
    contact_email: ContactEmail | None = Field(None, alias="contactEmail")
    contact_name: ContactName | None = Field(None, alias="contactName")
    contact_phone: ContactPhone | None = Field(None, alias="contactPhone")
    data_message: DataMessage | None = Field(None, alias="dataMessage")
    edit_message: EditMessage | None = Field(None, alias="editMessage")
    error: Error | None = None
    group_info: GroupInfo | None = Field(None, alias="groupInfo")
    mention: Mention | None = None
    message_envelope: MessageEnvelope | None = Field(None, alias="messageEnvelope")
    payment: Payment | None = None
    pin_message: PinMessage | None = Field(None, alias="pinMessage")
    poll_create: PollCreate | None = Field(None, alias="pollCreate")
    poll_terminate: PollTerminate | None = Field(None, alias="pollTerminate")
    poll_vote: PollVote | None = Field(None, alias="pollVote")
    preview: Preview | None = None
    quote: Quote | None = None
    quoted_attachment: QuotedAttachment | None = Field(None, alias="quotedAttachment")
    reaction: Reaction | None = None
    receipt_message: ReceiptMessage | None = Field(None, alias="receiptMessage")
    recipient_address: RecipientAddress | None = Field(None, alias="recipientAddress")
    remote_delete: RemoteDelete | None = Field(None, alias="remoteDelete")
    send_message_result: SendMessageResult | None = Field(
        None, alias="sendMessageResult"
    )
    shared_contact: SharedContact | None = Field(None, alias="sharedContact")
    sticker: Sticker | None = None
    story_context: StoryContext | None = Field(None, alias="storyContext")
    story_message: StoryMessage | None = Field(None, alias="storyMessage")
    sync_data_message: SyncDataMessage | None = Field(None, alias="syncDataMessage")
    sync_message: SyncMessage | None = Field(None, alias="syncMessage")
    sync_read_message: SyncReadMessage | None = Field(None, alias="syncReadMessage")
    sync_story_message: SyncStoryMessage | None = Field(None, alias="syncStoryMessage")
    text_style: TextStyle | None = Field(None, alias="textStyle")
    typing_message: TypingMessage | None = Field(None, alias="typingMessage")
    unpin_message: UnpinMessage | None = Field(None, alias="unpinMessage")
    attachments: list[Attachment] | None = None
    mentions: list[Mention] | None = None
    previews: list[Preview] | None = None
    contacts: list[SharedContact] | None = None
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")
