# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import AliasChoices, BaseModel, Field


class Attachment(BaseModel):
    caption: str | None = None
    content_type: str | None = Field(default=None, alias="contentType")
    remote_filename: str | None = Field(
        default=None,
        serialization_alias="filename",
        validation_alias=AliasChoices("filename", "remote_filename"),
    )
    height: int | None = None
    local_filename: str | None = Field(
        default=None,
        serialization_alias="id",
        validation_alias=AliasChoices("id", "local_filename"),
    )
    is_voice_note: bool = Field(..., alias="isVoiceNote")
    size: int | None = None
    upload_timestamp: int | None = Field(default=None, alias="uploadTimestamp")
    width: int | None = None
