# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field


class GroupCallUpdate(BaseModel):
    era_id: str | None = Field(default=None, alias="eraId")
