# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .admin_delete import AdminDelete
from .attachment import Attachment
from .edit_message import EditMessage
from .group_call_update import GroupCallUpdate
from .group_info import GroupInfo
from .mention import Mention
from .payment import Payment
from .pin_message import PinMessage
from .poll_create import PollCreate
from .poll_terminate import PollTerminate
from .poll_vote import PollVote
from .preview import Preview
from .quote import Quote
from .reaction import Reaction
from .remote_delete import RemoteDelete
from .shared_contact import SharedContact
from .sticker import Sticker
from .story_context import StoryContext
from .text_style import TextStyle
from .unpin_message import UnpinMessage


class SyncDataMessage(BaseModel):
    admin_delete: AdminDelete | None = Field(default=None, alias="adminDelete")
    attachments: list[Attachment] | None = None
    contacts: list[SharedContact] | None = None
    destination: str | None = None
    destination_number: str | None = Field(default=None, alias="destinationNumber")
    destination_uuid: str | None = Field(default=None, alias="destinationUuid")
    edit_message: EditMessage | None = Field(default=None, alias="editMessage")
    expires_in_seconds: int | None = Field(default=None, alias="expiresInSeconds")
    group_call_update: GroupCallUpdate | None = Field(
        default=None, alias="groupCallUpdate"
    )
    group_info: GroupInfo | None = Field(default=None, alias="groupInfo")
    has_profile_key: bool | None = Field(default=None, alias="hasProfileKey")
    is_end_session: bool | None = Field(default=None, alias="isEndSession")
    is_expiration_update: bool | None = Field(default=None, alias="isExpirationUpdate")
    is_profile_key_update: bool | None = Field(default=None, alias="isProfileKeyUpdate")
    mentions: list[Mention] | None = None
    message: str | None = None
    payment: Payment | None = None
    pin_message: PinMessage | None = Field(default=None, alias="pinMessage")
    poll_create: PollCreate | None = Field(default=None, alias="pollCreate")
    poll_terminate: PollTerminate | None = Field(default=None, alias="pollTerminate")
    poll_vote: PollVote | None = Field(default=None, alias="pollVote")
    previews: list[Preview] | None = None
    quote: Quote | None = None
    reaction: Reaction | None = None
    remote_delete: RemoteDelete | None = Field(default=None, alias="remoteDelete")
    sticker: Sticker | None = None
    story_context: StoryContext | None = Field(default=None, alias="storyContext")
    text_styles: list[TextStyle] | None = Field(default=None, alias="textStyles")
    timestamp: int | None = None
    unpin_message: UnpinMessage | None = Field(default=None, alias="unpinMessage")
    view_once: bool | None = Field(default=None, alias="viewOnce")
